FROM openjdk:8-jdk
WORKDIR /prometheus-aom-huaweicloud-java-demo
ADD target/prometheus-aom-huaweicloud-java-demo-*.jar /prometheus-aom-huaweicloud-java-demo/prometheus-aom-huaweicloud-java-demo.jar
CMD ["java","-jar","prometheus-aom-huaweicloud-java-demo.jar"]