apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-prometheus-aom-huaweicloud-java-demo1 # 填写一个唯一名称
  namespace: aom-custom-metrics-demo # namespace固定，不要修改
spec:
  endpoints:
  - interval: 30s
    port: cce-service-0 # 填写service yaml中Prometheus Exporter对应的Port的Name
    path: /actuator/prometheus  # 填写Prometheus Exporter对应的Path的值，不填默认/metrics
  namespaceSelector:  # 选择要监控service所在的namespace
    matchNames:
    - aom-custom-metrics-demo 
  selector: # 填写要监控service的Label值，以定位目标service
    matchLabels:
      app: prometheus-aom-huaweicloud-java-demo 
